### ISSUE TITLE
Fail to get dependency `mokutil`

### ISSUE THREAD

**Issue by taraxacum45e9a** [nus-ncl/intel-sgx-ansible-playbook#3]
Just as the title says, `mokutil` doesn't come with Ubuntu, and the playbook didn't install it before using.

**Comment by ariscahyadi** [comment]
Please add the `mokutil` installation between these two lines.
 

> After a first run, we do not need to regenerate the certificate. Verify with mokutil the list of enrolled certificate
.....
> name: "[DRIVER] Get the list of enrolled certificate in MOK"
